package bjj.domain;

public enum Position {
    STANDING,
    CLOSED_GUARD_TOP,
    CLOSED_GUARD_BOTTOM,
    OPEN_GUARD_TOP,
    OPEN_GUARD_BOTTOM,
    HALF_GUARD_TOP,
    HALF_GUARD_BOTTOM,
    SIDE_CONTROL_TOP,
    SIDE_CONTROL_BOTTOM,
    MOUNT_TOP,
    MOUNT_BOTTOM,
    BACK_CONTROL_TOP,
    BACK_CONTROL_BOTTOM,
    TURTLE_TOP,
    TURTLE_BOTTOM,
    KNEE_ON_BELLY_TOP,
    KNEE_ON_BELLY_BOTTOM,
    NORTH_SOUTH_TOP,
    NORTH_SOUTH_BOTTOM
}
